### PR TITLE
Flend master

### PR DESCRIPTION
**Pull request by ironwren**

### CODE REVIEW

**Comment by flend** [comment]
Looks like some interesting changes, if you do want to push some individually to my repo in future!

**Comment by ironwren** [comment]
I just made took all the features off, simplified the UI, and made it so it works just by running `docker-compose up`
image
@flend is any of this useful to you?

**Comment by flend** [comment]
I'll probably just take a look - might use your docker file for
inspiration, thanks :)

**Comment by ironwren** [comment]
@flend I wonder if using react/solidjs as the renderer might boost performance by only rendering tiles that change?

**Pull request closed without merging**
